server:
  port:9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

#      resillence config
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      retailerItemBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowsType: COUNT_BASED

