#server:
#  port: 9091
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/microservices
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true

server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

